### PR TITLE
#159647816 add recent questions page

### PR DESCRIPTION
**Pull request by asheux**
#### What does this PR do?

This PR creates the a page where users can view recently asked questions in the app

#### How should this be manually tested?
- clone the repo
```
$ git clone https://github.com/asheuh/StackOverflow-lite
$ cd StackOverflow-lite/UI/templates/mains
$ [your browser] home.html
```

#### What are the relevant pivotal tracker stories?
[159647816](https://www.pivotaltracker.com/n/projects/2189345/stories/159647816)
recent

### CODE REVIEW

**Comment by Eyansky** [comment]
Looks good to me

**Comment by asheux** [comment]
Thanks man, for the feedback

**Comment by Enockkenya** [comment]
crazy man! hands down great work

**Comment by ghost** [comment]
very Good.Visually appealing too

**Comment by Tony-Ndichu** [comment]
Dope stuff, keep it up

**Pull request merged**
