### PR TITLE
#159650798 create question and answer details page

### PR DESCRIPTION
**Pull request by asheux**
#### What does this PR do?

This PR creates the details page for users to view the whole question and answers to the question

#### How should this be manually tested?
- clone the repo
```
$ git clone https://github.com/asheuh/StackOverflow-lite
$ cd StackOverflow-lite/UI/templates/mains
$ [your browser] details.html
```

#### What are the relevant pivotal tracker stories?
[159650798](https://www.pivotaltracker.com/n/projects/2189345/stories/159650798)
details

### CODE REVIEW

**Comment by Enockkenya** [comment]
world class

**Comment by ghost** [comment]
Dope

**Comment by Eyansky** [comment]
Nice design

**Comment by asheux** [comment]
Thanks guys

**Comment by Gidraf** [comment]
It's nice

**Comment by vmuthabuku** [comment]
nice one

**Comment by evamaina** [comment]
Nice

**Comment by evamaina** [comment]
Nice

**Comment by asheux** [comment]
Thank you all.

**Pull request merged**
