### PR TITLE
#159587198 impliment my css framework

### PR DESCRIPTION
**Pull request by asheux**
#### What does this PR do?
- Implements the css framework to use for styling pages

#### What are the relevant pivotal tracker stories?
[159587198](https://www.pivotaltracker.com/n/projects/2189345)

### CODE REVIEW

**Comment by njorogetimk** [comment]
please include instructions on how to test this. that is, if I needed to test if your css is functioning right.

**Comment by TheSteelGuy** [comment]
So you basically have a CSS file with no pages it styles.. I wonder how you this works because CSS oughts to be styling something....

**Comment by asheux** [comment]
@njorogetimk I will do just that.

**Comment by asheux** [comment]
@TheSteelGuyI am testing with the css using simple pages that i don't really have to push to github. When im sure the css is set then i can use it to create the pages.

**Pull request merged**
